name: Evolution / Documentation
description: Describe an evolution or documentation task
labels: [evolution, documentation]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Context and motivation behind this evolution.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Work description
      description: Detail the work to be done.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: List each criterion as a checkbox. Check each one once completed.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: comments
    attributes:
      label: Additional comments
